from fastapi import FastAPI, HTTPException  # Importa FastAPI e la gestione delle eccezioni
from .crud import autentica_utente, get_ordini_cliente, get_dettagli_ordine, get_info_ordine  # Importa le funzioni CRUD
from .VALIDAZIONEDATI import LoginRequest  # Importa il modello per il login

app = FastAPI()  # Crea l'applicazione FastAPI

# Endpoint di health check (ping)
@app.get("/ping")
def ping():
    """
    Endpoint di test per verificare che il server sia attivo.
    """
    return {"status": "ok"}

# Generated by Copilot  
# Endpoint di login (autenticazione utente)
@app.post("/login")
def login(request: LoginRequest):
    """
    Verifica le credenziali dell'utente (codice e partita IVA).
    """
    if autentica_utente(request.ancodice, request.anpariva):
        return {"login": "success"}
    else:
        raise HTTPException(status_code=401, detail="Credenziali non valide")

# Endpoint per ottenere la lista degli ordini di un cliente
@app.get("/ordini/{ancodice}")
def lista_ordini(ancodice: str):
    """
    Restituisce la lista dei codici ordine associati a un cliente.
    TODO: Puoi aggiungere un modello di risposta per una struttura più chiara.
    """
    ordini = get_ordini_cliente(ancodice)
    return {"ordini": ordini}

# Endpoint per ottenere i dettagli di un ordine
@app.get("/ordini/dettagli/{mvserial}")
def dettagli_ordine(mvserial: str):
    """
    Restituisce i dettagli di un ordine dato il suo codice.
    TODO: Puoi aggiungere un modello di risposta per una struttura più chiara.
    """
    dettagli = get_dettagli_ordine(mvserial)
    return {"dettagli": dettagli}

# Generated by Copilot
# Endpoint per ottenere le informazioni di un ordine (inclusa la data)
@app.get("/ordini/info/{mvserial}")
def info_ordine(mvserial: str):
    """
    Restituisce le informazioni di un ordine (codice e data) dato il suo MVSERIAL.
    """
    info = get_info_ordine(mvserial)
    if info:
        return {"info": info}
    else:
        raise HTTPException(status_code=404, detail="Ordine non trovato")

# Puoi aggiungere altri endpoint o personalizzare la gestione delle richieste secondo le tue esigenze