# VALIDAZIONEDATI.py
# Modelli Pydantic per la validazione e la struttura dei dati tra API e database

from pydantic import BaseModel
from typing import List
from datetime import date

# Generated by Copilot
# Modello per la richiesta di login
class LoginRequest(BaseModel):
    ancodice: str  # Codice utente
    anpariva: str  # Partita IVA

# Modello per il dettaglio di un ordine (es: quantità)
class DettaglioOrdine(BaseModel):
    mqtaum1: float  # Quantità dell'articolo (corrisponde a MVQTAUM1 nel database)
    nome_articolo: str  # Nome dell'articolo

# Modello per un ordine
class Ordine(BaseModel):
    mvserial: str  # Numero seriale dell'ordine (corrisponde a MVSERIAL, char(10) nel database)
    mvdatreg: date  # Data di registrazione (corrisponde a MVDATREG, datetime nel database)
    dettagli: List[DettaglioOrdine]  # Lista dei dettagli dell'ordine

# Modello per la risposta al client
class RispostaCliente(BaseModel):
    cliente: str  # Codice cliente (può corrispondere a MVCODCON o ANCODICE)
    ordini: List[Ordine]  # Lista degli ordini del cliente

# Puoi ridefinire i nomi dei campi o aggiungere altri modelli secondo le tue esigenze 